import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source project: Music Pro
*/`;

const prod = process.argv.includes("production") || process.env.NODE_ENV === "production";
const nodeBuiltins = [...new Set([...builtinModules, ...builtinModules.map((name) => `node:${name}`)])];

await esbuild.build({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@electron/remote", ...nodeBuiltins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "dist/main.js"
});
